# Generated by Django 4.2.5 on 2024-06-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvr', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_logo', models.URLField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('contactperson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contactperson')),
            ],
            options={
                'verbose_name': 'Manufacture',
                'verbose_name_plural': 'Manufactures',
                'db_table': 'manufacture',
            },
        ),
    ]
