# Generated by Django 4.2.5 on 2024-06-04 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacture',
            old_name='contactperson_id',
            new_name='contactperson',
        ),
    ]
