# Generated by Django 4.2.5 on 2023-10-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='picture_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
