# Generated by Django 4.2.5 on 2023-10-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_alter_manufacture_picture_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='contactperson',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='cvr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='picture_logo',
            field=models.ImageField(blank=True, null=True, upload_to='manufactures/'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
