# Generated by Django 4.2.5 on 2023-10-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0006_alter_manufacture_cvr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='contactperson',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='cvr',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='name',
            field=models.CharField(default='Kim', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
