# Generated by Django 4.2.5 on 2023-11-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0007_alter_manufacture_contactperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='picture_logo',
            field=models.URLField(),
        ),
    ]
