# Generated by Django 4.2.5 on 2024-05-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('manufacture', '0008_alter_manufacture_picture_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacture',
            name='contactperson',
        ),
        migrations.AddField(
            model_name='manufacture',
            name='contactperson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contactperson'),
        ),
    ]
