# Generated by Django 4.2.5 on 2024-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0003_alter_vessel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(choices=[('Container Ship', 'Container Ship'), ('Tanker Ship', 'Tanker Ship'), ('Passenger Ship', 'Passenger Ship'), ('War Ship', 'War Ship'), ('Unspecified', 'Unspecified')], default='Unspecified', max_length=100),
        ),
    ]
