# Generated by Django 4.2.5 on 2024-06-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_customer_cases_alter_customer_name'),
        ('vessel', '0004_alter_vessel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='vessel_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases', to='customer.customer'),
            preserve_default=False,
        ),
    ]
