# Generated by Django 4.2.5 on 2024-06-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cost_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('is_unique', models.BooleanField(default=0)),
                ('manufacture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.manufacture')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('unique_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50)),
                ('custom_price', models.IntegerField(blank=True, null=True)),
                ('status_shipping', models.CharField(choices=[('Arrived', 'Arrived'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped'), ('Not Sent', 'Not Sent')], default='Shipped', max_length=150)),
                ('status_payment', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Awaiting Payment', 'Awaiting Payment'), ('Invoice Sent', 'Invoice Sent'), ('Invoice Not Created', 'Invoice Not Created')], max_length=150)),
                ('case', models.ManyToManyField(to='case.case')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_products', to='product.product')),
            ],
            options={
                'verbose_name': 'Unique_product',
                'verbose_name_plural': 'Unique_products',
                'db_table': 'unique_product',
            },
        ),
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('qty', models.IntegerField()),
                ('case', models.ManyToManyField(to='case.case')),
            ],
            options={
                'verbose_name': 'Simple_product',
                'verbose_name_plural': 'Simple_products',
                'db_table': 'simple_product',
            },
            bases=('product.product',),
        ),
    ]
