# Generated by Django 4.2.5 on 2023-11-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('product', '0001_initial'), ('product', '0002_rename_isdeleted_product_is_deleted'), ('product', '0003_simple_product_remove_product_serial_number_and_more'), ('product', '0004_alter_composite_product_options_and_more'), ('product', '0005_remove_simple_product_product_ptr_and_more')]

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('cost_price', models.IntegerField()),
                ('retail_price', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('manufacture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacture.manufacture')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
    ]
