# Generated by Django 4.2.5 on 2024-06-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniqueproduct',
            old_name='product_id',
            new_name='product',
        ),
    ]
