# Generated by Django 4.2.5 on 2023-10-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
