# Generated by Django 4.2.5 on 2024-06-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_id_uniqueproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueproduct',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
