# Generated by Django 4.2.5 on 2023-10-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_isdeleted_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simple_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
            ],
            bases=('product.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.CreateModel(
            name='Unique_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('serial_number', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Unique_product',
                'verbose_name_plural': 'Unique_products',
                'db_table': 'unique_product',
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='Composite_product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('serial_number', models.CharField(max_length=100)),
                ('component_list', models.ManyToManyField(related_name='composite_products', to='product.product')),
            ],
            options={
                'verbose_name': 'Composite_product',
                'verbose_name_plural': 'Composite_products',
                'db_table': 'composite_product',
            },
            bases=('product.product',),
        ),
    ]
