# Generated by Django 4.2.5 on 2024-06-04 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('product', '0003_alter_uniqueproduct_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='case',
        ),
        migrations.AddField(
            model_name='uniqueproduct',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unique_products', to='case.case'),
        ),
    ]
