# Generated by Django 4.2.5 on 2023-11-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_simple_product_remove_product_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composite_product',
            options={'ordering': ['name'], 'verbose_name': 'Composite_product', 'verbose_name_plural': 'Composite_products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='unique_product',
            options={'ordering': ['serial_number'], 'verbose_name': 'Unique_product', 'verbose_name_plural': 'Unique_products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_product',
        ),
    ]
