# Generated by Django 4.2.5 on 2024-06-04 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('product', '0004_remove_uniqueproduct_case_uniqueproduct_case'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleproduct',
            name='case',
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_products', to='case.case'),
        ),
    ]
