# Generated by Django 4.2.5 on 2023-11-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_type_product_qty_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('frugal', 'Frugal'), ('wrist', 'Wrist'), ('copenhagen', 'Copenhagen'), ('amsterdam', 'Amsterdam')], default='frugal', max_length=150),
        ),
    ]
