# Generated by Django 4.2.5 on 2024-05-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0007_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='defualt', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SimpleProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True, serialize=False,
                                                     to='product.product')),
                ('qty', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Simple_product',
                'verbose_name_plural': 'Simple_products',
                'db_table': 'simple_product',
                'ordering': ['name'],
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                     parent_link=True, primary_key=True, serialize=False,
                                                     to='product.product')),
                ('serial_number', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_price', models.IntegerField(blank=True, null=True)),
                ('status_shipping', models.CharField(choices=[('Frugal', 'Frugal'), ('Wrist', 'Wrist'),
                                                              ('Copenhagen', 'Copenhagen'),
                                                              ('Amsterdam', 'Amsterdam')],
                                                     default='frugal',max_length=150)),
                ('status_payment', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Unique_product',
                'verbose_name_plural': 'Unique_products',
                'db_table': 'unique_product',
                'ordering': ['name'],
            },
            bases=('product.product',),
        ),
    ]
