# Generated by Django 4.2.5 on 2024-06-03 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_remove_case_case_products_delete_caseproduct'),
        ('product', '0008_remove_product_location_remove_product_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simpleproduct',
            options={'verbose_name': 'Simple_product', 'verbose_name_plural': 'Simple_products'},
        ),
        migrations.AlterModelOptions(
            name='uniqueproduct',
            options={'ordering': ['serial_number'], 'verbose_name': 'Unique_product', 'verbose_name_plural': 'Unique_products'},
        ),
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='location',
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='case',
            field=models.ManyToManyField(to='case.case'),
        ),
        migrations.AddField(
            model_name='simpleproduct',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='simple_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='uniqueproduct',
            name='case',
            field=models.ManyToManyField(to='case.case'),
        ),
        migrations.AddField(
            model_name='uniqueproduct',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='unique_product', to='product.simpleproduct'),
        ),
        migrations.AlterField(
            model_name='uniqueproduct',
            name='status_payment',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Awaiting Payment', 'Awaiting Payment'), ('Invoice Sent', 'Invoice Sent'), ('Invoice Not Created', 'Invoice Not Created')], max_length=150),
        ),
        migrations.AlterField(
            model_name='uniqueproduct',
            name='status_shipping',
            field=models.CharField(choices=[('Arrived', 'Arrived'), ('Shipping', 'Shipping'), ('Shipped', 'Shipped'), ('Not Sent', 'Not Sent')], default='frugal', max_length=150),
        ),
    ]
