# Generated by Django 4.2.5 on 2024-06-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_simpleproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniqueproduct',
            options={'verbose_name': 'Unique_product', 'verbose_name_plural': 'Unique_products'},
        ),
        migrations.RemoveField(
            model_name='simpleproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
