# Generated by Django 4.2.5 on 2023-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_picture',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
