# Generated by Django 4.2.5 on 2024-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_customer_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cases',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
