# Generated by Django 4.2.5 on 2024-06-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='followers',
        ),
    ]
