# Generated by Django 4.2.5 on 2023-10-24 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vessel', '0002_vessel_imo_vessel_type'),
        ('product', '0002_rename_isdeleted_product_is_deleted'),
        ('customer', '0001_initial'),
        ('case', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('setup', 'Setup in Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('done', 'Done')], default='open', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='followers',
            field=models.ManyToManyField(related_name='following_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('courtesy', 'Courtesy')], default='unpaid', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vessel.vessel'),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cases', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='case',
            name='product_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('setup', 'Setup in Progress'), ('closed', 'Closed')], default='open', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_products',
            field=models.ManyToManyField(related_name='cases', to='case.caseproduct'),
        ),
    ]
