# Generated by Django 4.2.5 on 2024-06-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_case_invoice_case_project_manager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_products',
        ),
        migrations.DeleteModel(
            name='CaseProduct',
        ),
    ]
