# Generated by Django 4.2.5 on 2024-06-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_remove_case_case_products_delete_caseproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='product_owner',
            new_name='case_manager',
        ),
        migrations.RemoveField(
            model_name='case',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='case',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='case',
            name='project_manager_name',
        ),
    ]
