# Generated by Django 4.2.5 on 2024-06-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0009_rename_product_owner_case_case_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='total_price',
        ),
    ]
