# Generated by Django 4.2.5 on 2024-06-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_remove_case_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='invoice',
        ),
    ]
